### ISSUE TITLE
Register as a bower component?

### ISSUE THREAD

**Issue by seiyria** [joshaven/string_score#19]
Hiya! I like this plugin, and I was wondering if you'd be willing to [register it as a bower component](http://devhike.blogspot.com/2013/06/how-to-register-your-library-or.html)?

**Comment by kdabir** [comment]
+1

**Comment by karlnp** [comment]
I like it too, and I'm also behind this suggestion!

**Comment by AAudusseau** [comment]
+1

**Comment by joshaven** [comment]
I ran the bower install and I expect all is fine except it asks what module this exposes.  I answered global but I really don't know.  Can someone enlighten me as to how a script that extends the global String object exposes modules?

Here is the bower.json file that was generated...

    {
      "name": "string_score",
      "description": "String Scoring Algorithm packaged for NodeJS",
      "main": "string_score.js",
      "authors": [
        "Joshaven Potter <yourtech@gmail.com>"
      ],
      "license": "MIT",
      "keywords": [
        "string",
        "score",
        "string_score"
      ],
      "homepage": "https://github.com/joshaven/string_score",
      "moduleType": [
        "globals"
      ],
      "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
      ]
    }

**Comment by GaloisGirl** [comment]
Meanwhile, I smoothly installed it by doing:
`bower install --save 'git://github.com/joshaven/string_score.git#e85369c'`
e85369c being the id of the latest commit.

**Comment by seiyria** [comment]
Installing by commit hashes is doable but not at all useful, since you can't tell what tag it is initially, so you have no idea what you're actually running, except that it's a specific commit.

**Comment by GaloisGirl** [comment]
The use I get out of it is knowing the whole team will have the same version.

But of course, I'm keeping my fingers crossed for getting it registered.

**Comment by joshaven** [comment]
If someone wants to send me a pull request for the intragrations then I'd
be happy to pull it. I just don't want to make untested chances and I don't
know anything about the context this is being used in.

On Wednesday, March 2, 2016, GaloisGirl <notifications@github.com> wrote:

> The use I get out of it is knowing the whole team will have the same
> version.
>
> But of course, I'm keeping my fingers crossed for getting it registered.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshaven/string_score/issues/19#issuecomment-191432411>
> .
>


-- 
"Without our utmost care and diligence in the investigation of the truth,
we must be contented to walk in the shades of ignorance and error." - John
Owen 1678

**Comment by marcomafessolli** [comment]
I did it running `bower install string_score_ext --save`. 

For those who user `wiredep` to inject bower dependencies into `index.html`, add this at `bower.json`

```
"overrides": {
    "string_score_ext": {
      "main": "string_score.js"
    }
  }
```

**Comment by joshaven** [comment]
I added that text to the bower.json... Please confirm that it is correct.  I've never used bower so I'm just crossing my fingers hoping this file is helpful to users.   Thanks.  If there are problems with the file then I would greatly appreciate someone who can correct it and confirm the corrections sends me a patch or a pull request.
