### ISSUE TITLE
Add LICENSE to repository

### ISSUE THREAD

**Issue by chrisdias** [joshaven/string_score#25]
Hi!  I see that the readme links to the standard MIT License, but would it be possible to include a LICENSE file in the repository itself with the MIT license text and copyright statement in it? 

This practice makes it much easier for us to use the code and attribute it properly in our product.  

Thanks!

**Comment by joshaven** [comment]
I added the MIT License to the repo but didn't release another tagged version.  Does this make things easy enough for you?  Also, out of interest I would be happy to hear how you are able to put this code to use.

**Comment by chrisdias** [comment]
This is awesome, thank you!  We're using this is in [VS Code](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/scorer.ts) to provide fuzzy search in our Command Palette.
