### ISSUE TITLE
Feature-Request: closest/best match

### ISSUE THREAD

**Issue by hdf** [joshaven/string_score#28]
Would be nice, if we could do this: `"My string".closest([array of strings])` and would give back the index(es) of the best match(es). (Multiple results if their score is the same, but the content is not.)

**Comment by joshaven** [comment]
This is a perfect example of how string score can be used. You could use the each method of underscore js to give you an array of string scores and use the min or max method of underscore to give you the best or worst matches.

**Comment by hdf** [comment]
I made a pull request for posterity, in case someone would like to see a working example. An important thing to remember is, what we are comparing to what. Are we comparing many strings to one string, or one string to many? The results will be different.
This solution compares many to one. Meaning you can check if from a selection, what is most similar to your string. It is not for checking what your string is most similar to. (Maybe I should make one for that too...)
